### ISSUE TITLE
Can this help me compose another store like a reducer?

### ISSUE THREAD

**Issue by bholloway** [loggur/redux-replicate#2]
I have a new store `A` that needs to integrate some other existing stores `B` and `C`.

I would like to somehow wrap the existing stores so that they look like reducers.

This would mean something like:

* The state composition of `A`:
  ```
  {
      b: B.getState(),
      c: C.getState(),
      a: <state intrinsic to A>
  }
  ```

* Actions on `A.dispatch()` would imply `B.dispatch()` and `C.dispatch()`.

* Change on `B` or `C` implies change on `A`.

* Any behind-the-scenes state change on `A` (e.g. `redux-devtools` rollback) also updates the state of `B` and `C` appropriately.

Is this within the capabilities of `redux-replicate` to do this? Or could you suggest a better solution.

**Comment by timbur** [comment]
You could use `redux-replicate` to do this... But may I ask why these stores a, b, and c are separate to begin with?  Sounds like they should probably just be a single store since they heavily depend on one another.

**Comment by bholloway** [comment]
Change management.

We have is a large app with multiple teams working from one repository and
many existing flux stores.

To move to Redux we need to depend on these existing stores in the short
term.

The medium to long term aim being to migrate those flux stores to Redux
stores and then to reducers.

In the mean time we want to write nice Redux code that won't have to change.

Can you give me a brief overview as to how I this could work using the
available API?

**Comment by timbur** [comment]
I see.

If you're using React, you may want to check out https://github.com/loggur/react-redux-provide, specifically the [`subscribeTo`](https://github.com/loggur/react-redux-provide#subscribeto) and/or [`subscribers`](https://github.com/loggur/react-redux-provide#subscribers) sections, which allows you to easily "link" provider stores.  But that of course depends on whether or not you'd want to use `react-redux-provide`, and I'm not sure how well it would play with your existing codebase.  It is an abstraction designed to address many of the pain points and boilerplate involved with vanilla Redux + React, while remaining fully compatible with everything within the Redux ecosystem.  There is a small learning curve, but I would wager that it's actually easier to grasp than vanilla Redux and helps enforce a cleaner, more manageable/reusable codebase.  The README grew to be pretty daunting though and will be turned into proper documentation soon.

If you're not using React or if you'd rather not give the provider paradigm a shot, you could probably get away with creating a replicator as simple as the following to tie your Redux stores together.

If you always want to dispatch the action throughout all other stores after reduction has completed on some store:
```js
// src/replicators/linkStores.js

import * as stores from '../stores/index';

const postReduction = ({ store, state, nextState, action }) => {
  for (let key in stores) {
    if (stores[key] !== store) {
      stores[key].dispatch({ ...action, originStore: store });
      // might be best to clone the action object for each dispatch
      // also might want to keep track of the store the action came from
    }
  }
};

export default { postReduction };
```

Or if you want to dispatch the action (or do whatever else) immediately as some store's state changes and only when the state has changed (if you're not using `replication.reducerKeys` you probably don't care about this one, as you could just compare `state === nextState` in `postReduction`):
```js
// src/replicators/linkStores.js

import * as stores from '../stores/index';
import { SOMETHING_CHANGED } from '../constants';

const onStateChange = ({ store, reducerKey, state, nextState, action }) => {
  for (let key in stores) {
    if (stores[key] !== store) {
      stores[key].dispatch({
        type: SOMETHING_CHANGED,
        originStore: store,
        reducerKey,
        state,
        nextState,
        action
      });
    }
  }
};

export default { onStateChange };
```

Or you can use a combination of the two:
```js
// src/replicators/linkStores.js

import * as stores from '../stores/index';

const onStateChange = ({ store, reducerKey, state, nextState, action }) => {
  // etc.
};

const postReduction= ({ store, action }) => {
  // etc.
};

export default { onStateChange, postReduction };
```

And there is also [`getInitialState`](https://github.com/loggur/redux-replicate#getinitialstate) and/or [`onReady`](https://github.com/loggur/redux-replicate#onready) if any stores' initial states depend on one another.  Lastly, in advance, don't worry about `handleQuery` within `redux-replicate`'s README, as it's meant to be used with providers.

As for how to apply the above replicator to each store, see the [example using `compose`](https://github.com/loggur/redux-replicate#example-using-compose) in the README.

None of the above code has been tested but it should (mostly) work.  :)

**Comment by bholloway** [comment]
Thanks @timbur, I could not ask for more. I will give that a try.

Please feel free to close the issue.

I took a look at `react-redux-provide` and almost raised an issue regarding the readme. I think I will go do that instead of polluting this issue.

**Comment by timbur** [comment]
Sure thing.  LMK how it goes!
